services:
  - type: web
    name: laptop-store-backend
    env: node
    buildCommand: cd server-node && npm install
    startCommand: cd server-node && npm start
    envVars:
      - key: NODE_ENV
        value: production
